baseURL = "https://dgraph.io/tour/"
languageCode = "en-us"
title = "A Tour of Dgraph"
theme="hugo-tutorials"
canonifyURLs = false

[[menu.main]]
  name = "DQL Introduction"
  url = "/intro/1/"
  identifier = "intro"
  weight = 1
  [menu.main.params]
    time = "9 min."
[[menu.main]]
  name = "DQL Basic Features"
  url = "/basic/1/"
  identifier = "basic"
  weight = 2
  [menu.main.params]
    time = "18 min."
[[menu.main]]
  name = "DQL Schema"
  url = "/schema/1/"
  identifier = "schema"
  weight = 3
  [menu.main.params]
    time = "13 min."
[[menu.main]]
  name = "DQL Data and More Data"
  url = "/moredata/1/"
  identifier = "moredata"
  weight = 4
  [menu.main.params]
    time = "8 min."
[[menu.main]]
  name = "DQL Query Blocks and Variables"
  url = "/blocksvars/1/"
  identifier = "blocksvars"
  weight = 5
  [menu.main.params]
    time = "12 min."
[[menu.main]]
  name = "DQL Search"
  url = "/search/1/"
  identifier = "search"
  weight = 6
  [menu.main.params]
    time = "14 min."
[[menu.main]]
  name = "GraphQL Introduction"
  url = "/graphqlintro/1/"
  identifier = "graphqlintro"
  weight = 7
  [menu.main.params]
    time = "9 min."
[[menu.main]]
  name = "GraphQL Basic Features"
  url = "/graphqlbasic/1/"
  identifier = "graphqlbasic"
  weight = 8
  [menu.main.params]
    time = "22 min."
[[menu.main]]
  name = "GraphQL Schema"
  url = "/graphqlschema/1/"
  identifier = "graphqlschema"
  weight = 9
  [menu.main.params]
    time = "11 min."
[[menu.main]]
  name = "GraphQL Search"
  url = "/graphqlsearch/1/"
  identifier = "graphqlsearch"
  weight = 10
  [menu.main.params]
    time = "7 min."
[[menu.main]]
  name = "GraphQL Data and More Data"
  url = "/graphqlmoredata/1/"
  identifier = "graphqlmoredata"
  weight = 11
  [menu.main.params]
    time = "6 min."



[params]
  [params.url]
    # Dgraph site
    dgraphHome = "https://dgraph.io"
    dgraphDocs = "https://docs.dgraph.io/"
    dgraphTour = "/"
    dgraphBlog = "https://dgraph.io/blog/"
    dgraphProduct = "https://dgraph.io/product"
    dgraphSolutions = "https://dgraph.io/solutions"
    dgraphPaper = "https://dgraph.io/paper"
    dgraphCaseStudies = "https://dgraph.io/casestudies"
    dgraphCommunity = "https://dgraph.io/community"
    dgraphLegal = "https://dgraph.io/legal-notices/cloud-terms"

    # Dgraph services
    dgraphPlay = "http://localhost:8001"
    dgraphPlayGraphQL = "http://localhost:8001/graphql"
    dgraphForum = "https://discuss.dgraph.io/"
    dgraphGitHub = "https://github.com/dgraph-io/dgraph"

    # Social media
    dgraphTwitter = "https://twitter.com/dgraphlabs"
    dgraphLinkedIn = "https://www.linkedin.com/company/dgraph-labs"
    dgraphYouTube = "https://www.youtube.com/channel/UCghE41LR8nkKFlR3IFTRO4w"
    # Local development
    localEndpoint = "http://localhost:8080"
    graphqlEndpoint = "http://localhost:8080/graphql"

  [params.menudesc]
    graphqlintro = "In this module you'll learn how to set up and run Dgraph for the GraphQL portion of this tour, and learn about graph databases."
    graphqlbasic = "Here you'll learn the basics of how to query graph data from Dgraph using GraphQL, and how to use and interpret the results."
    graphqlschema = "This module shows you how GraphQL schemas work inside Dgraph; and how to add, update, and delete data."
    graphqlmoredata = "Now that you have some experience with Dgraph and GraphQL, this module shows you how to work with some larger datasets."
    graphqlsearch = "In this module, you'll learn about Dgraph's search features with GraphQL."
    intro = "In this module you'll learn how to set up and run Dgraph with Docker for the DQL portion of this tour, and also learn about graph databases."
    basic = "Here you'll learn the basics of how to query graph data from Dgraph and how to use and interpret the results."
    schema = "This module shows you how schemas work inside Dgraph; and how to add, update, and delete data."
    moredata = "Now that you have some experience with Dgraph and DQL, this module shows you how to use the Live Loader tool to load large datasets.  You'll need this bigger dataset for the remaining sections of the tutorial."
    blocksvars = "This module shows you how to build more powerful queries with multiple query blocks and query variables."
    search = "In this module, you'll learn about Dgraph's search features with DQL."
