services:
  dgraph:
1    image: dgraph/standalone:v24.1.4
    container_name: tour-dgraph
    ports:
      - "8080:8080"
      - "9080:9080"
    volumes:
      - ./docker/dgraph:/dgraph

  ratel:
    image: dgraph/ratel:latest
    container_name: tour-ratel
    ports:
      - "8001:8000"
    depends_on:
      - dgraph
